# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0002_auto_20170323_1616'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Table')),
            ],
        ),
    ]
